### ISSUE TITLE
Engage visitors to become contributors

### ISSUE THREAD

**Issue by erikw** [xaizek/vim-like-pile#2]
Now that this is on GitHub, we should encourage visitors of 
https://vim.reversed.top/
to engage and become contributors as well!

I can imagine:
1. Add link to the repo on the about page
1.  Add a "Fork me on GitHub" banner, that projects do to signal that they are welcome to contribute to what they see.

For 2., I looked at a few options
* https://forkmeon.github.io/
* https://whatthefoo.github.io/fork-me-on-github/
* https://simonwhitaker.github.io/github-fork-ribbon-css/

and  think the last one would be easiest to integrate!

(I tried the last one but I was not having the right PHP version on my system, so I could not view the result)

**Comment by xaizek** [comment]
I actually dislike those "Fork me on GitHub" stripes. Always worry that they point to forking URL and have to check them. They also look out of place.

I've already added "contribute" link that doesn't add this ad-like visual noise and that should be prominent enough for anyone interested in submitting changes.

**Comment by erikw** [comment]
Makes sense. Thx!

I'll start sharing this website with my Vim-friends now :)
